<!-- Enter -->
<form class="form-signin" role="form" onsubmit="javascript:Login.btn_enter_click();return false;">
    <h2 class="form-signin-heading">Log in</h2>
    <input id="user" type="text" class="form-control" placeholder="User" maxlength="50" required autofocus>
    <input id="password" type="password" class="form-control" placeholder="Password" maxlength="50" required>

    <div id="signin_alert" class="alert alert-danger" style="display: none;">
    </div>

    <button id="btn_enter" class="btn btn-lg btn-primary btn-block" type="submit">Enter</button>
</form>
<!-- /Enter -->