<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">Defect</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="post_tipo" name="post_tipo">

                    <input type="hidden" id="rec_id">

                    <div class="form-group">
                        <label for="edt_name">Name</label>
                        <input type="text" class="form-control" id="edt_name" placeholder="Name" maxlength="30">
                    </div>

                    <div class="form-group">
                        <label for="edt_description">Description</label>
                        <input type="text" class="form-control" id="edt_description" placeholder="Description" maxlength="250">
                    </div>
                </form>
                
                <!-- ALERTAS -->
                <div id="alerta_form" class="alert alert-danger">
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->