<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">Poblo Status</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="post_tipo" name="post_tipo">

                    <input type="hidden" id="rec_id">

                    <div class="form-group">
                        <label for="edt_status">Status</label>
                        <input type="text" class="form-control" id="edt_status" placeholder="Status" maxlength="50">
                    </div>

                    <div class="form-group">
                        <label for="cbo_color">Color</label>
                         <span id="cor_exemplo" class="cor_exemplo badge" style="padding-right: 100px; float: right;">&nbsp;</span>
                        <select id="cbo_color" class="form-control select2" onchange="javascript: carrega_cor();">
                        </select>
                    </div>
                </form>
                
                <!-- ALERTAS -->
                <div id="alerta_form" class="alert alert-danger">
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->