<!-- MODAL DETALHE -->
<div class="modal" id="modal_down_commercial_invoice" tabindex="-1" role="dialog" aria-labelledby="modal_down_commercial_invoice_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_down_commercial_invoice');">&times;</button>
                <h4 class="modal-title" id="modal_down_commercial_invoice_label">Commercial Invoice</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_date">Date</label>
                            <input type="date" class="form-control" id="edt_ci_date">
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_number">Number</label>
                            <input type="text" class="form-control" id="edt_ci_number" placeholder="Commercial Invoice Number" maxlength="50">
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_dv">D/V (Ref)</label>
                            <input type="text" class="form-control" id="edt_ci_dv" placeholder="D/V" maxlength="50">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="edt_ci_client_notify_address">Client</label>
                            <textarea class="form-control" id="edt_ci_client_notify_address" placeholder="Client and Notify Address" rows="4" maxlength="650"  spellcheck="false"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="edt_ci_client_consignee">Consignee</label>
                            <textarea class="form-control" id="edt_ci_client_consignee" placeholder="Consignee" rows="4" maxlength="500" spellcheck="false"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_shipped_from">Shipped from</label>
                            <input type="text" class="form-control" id="edt_ci_shipped_from" placeholder="Shipped from" maxlength="50">
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_shipped_to">Shipped to</label>
                            <input type="text" class="form-control" id="edt_ci_shipped_to" placeholder="Shipped to" maxlength="50">
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-4">
                        <div class="form-group">
                            <label for="edt_ci_vessel">Vessel</label>
                            <input type="text" class="form-control" id="edt_ci_vessel" placeholder="Vessel" maxlength="50">
                        </div>
                    </div>
                </div>

                <div class="row">
                    
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <!-- Listagem produtos -->
                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="tbl_ci_products">
                                <thead>
                                    <tr>
                                        <th width="80px">Blocks</th>
                                        <th>Product</th>
                                        <th>Quality</th>
                                        <th class="text-right small text-info" style="width: 100px">Last Value</th>
                                        <th width="120px" class="text-right">USD</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <!-- itens -->
                                    <tr template-row style="display: none;">
                                        <td template-field="blocks">{blocks}</td>
                                        <td template-field="product_name">{product_name}</td>
                                        <td template-field="quality_name">{quality_name}</td>
                                        <td template-field="last_value" class="text-right small text-info">{last_value}</td>
                                        <td class="text-right">
                                            <input template-field="value" type="text" class="form-control input_number text-right" placeholder="0.00" >
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- /Listagem produtos -->
                    </div>
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" onclick="javascript:closeModal('modal_down_commercial_invoice');">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="javascript:btn_down_commercial_invoice_click();">
                    <span class="glyphicon glyphicon-download-alt"></span> Download
                </button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->