<!-- MODAL DETALHE -->
<div class="modal" id="modal_excel" tabindex="-1" role="dialog" aria-labelledby="modal_excel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_excel');">&times;</button>
                <h4 class="modal-title" id="modal_excel_label">Excel</h4>
            </div>
            <div class="modal-body">
            <p>The spreadsheet is being generated</p>
            <p>This may take a few minutes</p>
            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_excel');">Ok</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->