<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">New Truck</h4>
            </div>
            <div class="modal-body">
                   
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cbo_carrier">Carrier</label>
                            <select  id="cbo_carrier" class="cbo_carrier form-control " data-live-search="true">
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for"edt_new_truck">Truck Name</label>
                            <input type="text" class="form-control edt_new_truck" id="edt_new_truck"></input>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:send_new_truck();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->