<ol class="breadcrumb">
    <li><a>General</a></li>
    <li class="active">Qualities</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav>

    <!-- Listagem de pedreiras -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th style="width: 30px;">
                        Order
                    </th>
                    <th style="width: 120px;">
                        &nbsp;
                    </th>
                    <th>Quality Name</th>
                    <th>Block Type</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="order">{order}</td>
                    <td template-field="order_action">
                        <button type="button" class="btn btn-default" template-button="order_up">
                            <span class="glyphicon glyphicon-arrow-up"></span>
                        </button>
                        <button type="button" class="btn btn-default" template-button="order_down">
                            <span class="glyphicon glyphicon-arrow-down"></span>
                        </button>
                    </td>
                    <td template-field="name">{name}</td>
                    <td template-field="block_type">{block_type}</td>
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                <li><a href="#" template-button="edit">
                                    Edit
                                </a></li>
                                <li><a href="#" template-button="delete">
                                    Delete
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->