<ol class="breadcrumb">
    <li><a>Sale</a></li>
    <li class="active">Inspection Certificate</li>
</ol>

<!-- LISTAGEM -->
<div>

    <!--nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav-->

    <!-- Listagem de pedreiras -->
    <div class="row">
        <div class="col-md-2" style="width: 150px;">
            <div class="form-group">
                <label class="hidden-sm hidden-xs">&nbsp;</label>
                <input type="text" class="form-control" placeholder="Year" maxlength="4" id="edt_year" onkeyup="javascript:listar()">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label class="hidden-sm hidden-xs">&nbsp;</label>
                <select id="cbo_month_filter" class="form-control select2 select2-input" onchange="javascript:listar()">  
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">Octuber</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="cbo_filter_client">Filter lots of client</label>
                <select id="cbo_filter_client" class="form-control select2 select2-input">
                </select>
            </div>
        </div> 
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Invoice</th>
                    <th>Client</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="date_record">{date_record}</td>
                    <td template-field="id">{id}</td>
                    <td template-field="client_name">{client_name}</td>
                    <td >
                        <div class="pull-right">
                            <div class="btn-group">    
                            <button type="button" class="btn btn-default" template-button="select">
                                <span class="glyphicon glyphicon-download-alt"></span> PDF
                            </button>
                            <button type="button" class="btn btn-default" template-button="select_excel">
                                <span class="glyphicon glyphicon-list-alt"></span> Excel
                            </button>
                        </div>
                           <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    Action <span class="caret"></span>
                                </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" template-button="blocks">
                                            Blocks
                                        </a></li>
                                        <li template-menu="edit"><a href="#" template-button="edit">
                                            Edit
                                        </a></li>
                                        <li template-menu="delete"><a href="#" template-button="delete">
                                            Delete
                                        </a></li>
                                           <li template-menu="delete"><a href="#" template-button="email">
                                            E-Mail
                                        </a></li>
                                    </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- /Listagem de chamados -->
</div>

<!-- /LISTAGEM -->