<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">Schedule Inspection</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="post_tipo" name="post_tipo">

                    <input type="hidden" id="rec_id">

                    <div class="form-group">
                        <label for="edt_day">Day</label>
                        <input type="date" class="form-control" id="edt_day">
                    </div>

                    <!--div class="form-group">
                        <label for="edt_time">Time</label>
                        <input type="time" class="form-control" id="edt_time" placeholder="00:00">
                    </div-->

                    <div class="form-group">
                        <label for="cbo_quarry">Quarry</label>
                        <select id="cbo_quarry" class="form-control select2" multiple="multiple">
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="cbo_client">Client</label>
                        <select id="cbo_client" class="form-control select2 select2-input">
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="edt_obs">Observations</label>
                        <textarea class="form-control" id="edt_obs" placeholder="Observations" rows="6" maxlength="500" spellcheck="false"></textarea>
                    </div>

                </form>
                
                <!-- ALERTAS -->
                <div id="alerta_form" class="alert alert-danger">
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <div class="pull-right">
                    <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                    <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
                </div>
                <div class="text-left">
                    <button type="button" class="btn btn-danger btn-sm" id="btn_delete" onclick="javascript:$('#post_tipo').val(FORMULARIO.EXCLUIR);envia_detalhes();">Delete</button>
                </div>
                
                
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->
