<ol class="breadcrumb">
    <li><a>Sale</a></li>
    <li class="active">Schedule Inspection</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
       <div class="row">
            <div class="col-md-1">
                <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
                    <span class="glyphicon glyphicon-plus-sign"></span> New
                </button>
            </div>
            <!--div class="form-group col-md-3 navbar-left">
                <select id="cbo_quarry_filter" class="form-control select2 select2-input"></select>
            </div-->
            <div class="btn-group navbar-right" style="margin-right:15px;">
                <button type="button" class="btn btn-primary" id="btn_calendar" onclick="javascript:btn_visualizar('calendario');">
                    <span class="glyphicon glyphicon-calendar"></span>
                </button>
                <button type="button" class="btn btn-default" id="btn_list" onclick="javascript:btn_visualizar('lista');">
                    <span class="glyphicon glyphicon-list-alt"></span>
                </button>
            </div>              
            <div class="form-group col-md-3 navbar-right">
                <select id="cbo_month_filter" class="form-control select2 select2-input" onchange="javascript:listar()">  
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
            </div> 
            <div class="form-group col-md-1 navbar-right" style="width: 12%;">
                <input type="text" class="form-control" id="edt_year" placeholder="Year" onkeyup="javascript:listar()">
            </div>
        </div>
    </nav>

   

    <!-- Listagem de pedreiras -->
    <div class="table-responsive" id="div_listagem">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>Day</th>
                    <th>Time</th>
                    <th>Client Name</th>
                    <!--th>Quarry Name</th-->
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="day">{day}</td>
                    <!--td template-field="time">{time}</td-->
                    <td template-field="client_name">{client_name}</td>
                    <!--td template-field="quarry_name">{quarry_name}</td-->
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                <li><a href="#" template-button="edit">
                                    Edit
                                </a></li>
                                <li><a href="#" template-button="delete">
                                    Delete
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <div id="calendar" style="max-width: auto;"></div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->