<!-- MODAL DETALHE -->
<div class="modal" id="modal_reserve" tabindex="-1" role="dialog" aria-labelledby="modal_reserve_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_reserve');">&times;</button>
                <h4 class="modal-title" id="modal_reserve_label">Reserve</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="reserve_post_tipo">

                    <input type="hidden" id="reserve_rec_id">

                    <div class="form-group">
                        <label for="edt_reserve_block_number">Block Number</label>
                        <input type="text" class="form-control" id="edt_reserve_block_number" placeholder="Block Number" readonly="true">
                    </div>

                    <div class="form-group" id="reserve_client_block_number">
                        <label for="edt_reserve_client_block_number" style="display: none;">Client Block Number</label>
                        <input type="text" class="form-control" id="edt_reserve_client_block_number" placeholder="Optional" maxlength="50" style="display: none;">
                    </div>

                </form>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_reserve_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_reserve_save">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->