<!-- MODAL LISTA BLOCOS -->
<div class="modal bs-modal-lg" id="modal_add_block" tabindex="-1" role="dialog" aria-labelledby="modal_add_block_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_add_block');">&times;</button>
                <h4 class="modal-title" id="modal_add_block_label">Sobracolumay</h4>
            </div>
            <div class="modal-body">

                <div id="list_add">
                </div>

                <!-- template-table-add -->
                <div class="panel panel-default" style="display: none;" template-table-add>
                    <div class="panel-heading" style="padding: 5px" >
                        <h3 class="panel-title" style="font-weight: bold" template-title>Quarry</h3>
                        <div><span class="label label-primary" template-quality>Quality</span></div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table_block_list">
                            <thead>
                                <tr>
                                    <th>Block Number</th>
                                    <th colspan="3" class="text-center">Tot Meas</th>
                                    <th colspan="3" class="text-center">Net Meas</th>
                                    <th class="text-center">Vol</th>
                                    <th class="text-center">Weight</th>
                                    <th class="text-center">Obs.</th>
                                    <th class="text-center">Reserved</th>
                                    <th class="text-center">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- template-row -->
                                <tr template-row style="display: none;">
                                    <td template-field="block_number" style="width: 160px">
                                        <a template-field="block_number_a" href="#">{block_number}</a>
                                    </td>
                                    <td template-field="tot_c" style="width: 60px" class="text-right">{C}</td>
                                    <td template-field="tot_a" style="width: 60px" class="text-right">{A}</td>
                                    <td template-field="tot_l" style="width: 60px" class="text-right">{L}</td>
                                    <td template-field="net_c" style="width: 60px" class="text-right">{C}</td>
                                    <td template-field="net_a" style="width: 60px" class="text-right">{A}</td>
                                    <td template-field="net_l" style="width: 60px" class="text-right">{L}</td>
                                    <td template-field="net_vol" style="width: 80px" class="text-right">{Vol}</td>
                                    <td template-field="tot_weight" style="width: 90px" class="text-right">{Weight}</td>
                                    <td template-field="obs">{Obs}</td>
                                    <!--td style="width: 90px">
                                        <span template-field="reserved">{client_name}</span>
                                        <div class="btn-group btn-group-sm" style="float: right; margin: -5px;">
                                            <button type="button" class="btn btn-default" template-button="reserved">
                                                <span class="glyphicon glyphicon-search"></span>
                                            </button>
                                        </div>
                                    </td-->
                                    <td template-field="reserved" style="width: 90px">{reserved}</td>
                                    <td template-field="selected" style="width: 50px" class="text-center">
                                        <input type="checkbox">
                                    </td>
                                </tr>
                                <!-- /template-row -->
                            </tbody>
                        </table>
                        
                    </div>

                </div>
                <!-- /template-table-add -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_add_block_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_add_block_add">Ok</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL LISTA BLOCOS -->

<!-- MODAL LISTA BLOCOS -->
<div class="modal bs-modal-lg" id="modal_blocks_with_reserves" tabindex="-1" role="dialog" aria-labelledby="modal_blocks_with_reserves_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_blocks_with_reserves');">&times;</button>
                <h4 class="modal-title" id="modal_blocks_with_reserves_label">Blocks with reserves</h4>
            </div>
            <div class="modal-body">

                <p>The following blocks have reserves, if you continue, they will be lost.</p>

                <table class="table table-striped table-bordered table-hover" id="tbl_blocks_with_reserves">
                    <thead>
                        <tr>
                            <th>Block Number</th>
                            <th class="text-center">Quality</th>
                            <th class="text-center">Reserved</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- template-row -->
                        <tr template-row style="display: none;">
                            <td template-field="block_number" style="width: 160px">{block_number}</td>
                            <td template-field="quality_name" style="width: 60px" class="text-center">{quality_name}</td>
                            <td template-field="reserved_client_code" style="width: 60px" class="text-center">{reserved_client_code}</td>
                        </tr>
                        <!-- /template-row -->
                    </tbody>

                    
                </table>  

                

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_blocks_with_reserves_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_blocks_with_reserves_continue">Continue</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL LISTA BLOCOS -->