<ol class="breadcrumb">
    <li><a>Sale</a></li>
    <li><a href="<?= APP_URI ?>inspection/clients/">Inspection</a></li>
    <li class="active"><?= $client->code ?> - <?= $client->name ?></li>
</ol>

<div>

    <!-- MENU -->
    <div id="bl_menu_heading">
        <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
            <button type="button" class="btn btn-primary btn_bl_add">
                <span class="glyphicon glyphicon-plus-sign"></span> Add block
            </button>

            <div style="float: right">
                <button type="button" class="btn btn-primary btn_bl_finish">
                    <span class="glyphicon glyphicon-ok"></span> Finish
                </button>
            </div>
        </nav>
    </div>

    <!-- LISTAGEM -->
    <div>

        <div id="list">
        </div>

        <!-- template-table -->
        <div class="panel panel-default" style="display: none;" template-table>
            <div class="panel-heading" style="padding: 5px" >
                <h3 class="panel-title" style="font-weight: bold" template-title>Quarry</h3>
                <div><span class="label label-primary" template-quality>Quality</span></div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover table_block_list" id="tbl_listagem">
                    <thead>
                        <tr>
                            <th>Block Number</th>
                            <th colspan="3" class="text-center">Tot Meas</th>
                            <th colspan="3" class="text-center">Client Net Meas</th>
                            <th class="text-center">Vol</th>
                            <th class="text-center">Weight</th>
                            <th width="10px" class="text-center" data-toggle="tooltip" title="Compensation Measure" style="cursor: pointer;">C</th>
                            <th class="text-center">Obs.</th>
                            <th class="text-center">Client Block Number</th>
                            <th class="text-center">Status</th>
                        </tr>
                    </thead>
                    <tbody>

                        <!-- template-row -->
                        <tr template-row style="display: none;">
                            <td template-field="block_number" style="width: 150px">
                                <a template-field="block_number_a" href="#">{block_number}</a>
                            </td>
                            <td template-field="tot_c" style="width: 45px" class="text-right">{C}</td>
                            <td template-field="tot_a" style="width: 45px" class="text-right">{A}</td>
                            <td template-field="tot_l" style="width: 45px" class="text-right">{L}</td>
                            <td style="width: 50px" class="text-right">
                                <input template-field="sale_net_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 50px;">
                            </td>
                            <td style="width: 50px" class="text-right">
                                <input template-field="sale_net_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 50px;">
                            </td>
                            <td style="width: 50px" class="text-right">
                                <input template-field="sale_net_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 50px;">
                            </td>
                            <td style="width: 80px" class="text-right">
                                <span template-field="sale_net_vol">{vol}</span>
                                <br/>
                                <span template-field="sale_net_vol_diff" class="small">{vol_diff}</span>
                                <br/>
                                <span template-field="sale_net_vol_diff_per" class="small">{vol_diff_per}</span>
                            </td>
                            <td template-field="tot_weight" style="width: 70px" class="text-right">{weight}</td>
                            <td  style="width: 70px" class="text-center">
                                <input type="checkbox" template-field="compensation_measure">
                            </td>
                            <td template-field="obs">{Obs}</td>
                            <td style="width: 80px" class="text-left">
                                <input template-field="client_block_number" type="text" class="form-control input_number text-left" placeholder="Optional" maxlength="50" style="padding:3px; width: 100px;">
                            </td>
                            <!--td style="width: 90px">
                                <span template-field="reserved">{client_name}</span>
                                <div class="btn-group btn-group-sm" style="float: right; margin: -5px;">
                                    <button type="button" class="btn btn-default" template-button="reserved">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </div>
                            </td-->
                            <td template-field="confirmed" style="width: 120px">
                                <select class="form-control" style="width: 120px">
                                    <option value="1">Accepted</option>
                                    <option value="0">Refused</option>
                                </select>
                            </td>
                        </tr>
                        <!-- /template-row -->

                    </tbody>
                </table>
                
            </div>

        </div>
        <!-- /template-table -->
        
    </div>

    <!-- /LISTAGEM -->






    <div id="bl_menu_footer">
    </div>
    
</div>

<!-- /LISTAGEM -->