<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_confirm" tabindex="-1" role="dialog" aria-labelledby="modal_confirm_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_confirm');">&times;</button>
                <h4 class="modal-title" id="modal_confirm_label">Confirm Inspection</h4>
            </div>
            <div class="modal-body">
                
                <div id="list_confirm">
                </div>

                <!-- template-table -->
                <div class="panel panel-default" style="display: none;" template-table-confirm>
                    <div class="panel-heading" style="padding: 5px" >
                        <h3 class="panel-title" style="font-weight: bold" template-title>Quarry</h3>
                        <div><span class="label label-primary" template-quality>Quality</span></div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table_block_list" id="tbl_listagem_confirm">
                            <thead>
                                <tr>
                                    <th>Block Number</th>
                                    <th colspan="3" class="text-center">Tot Meas</th>
                                    <th colspan="3" class="text-center">Net Meas</th>
                                    <th class="text-center">Vol</th>
                                    <th class="text-center">Weight</th>
                                    <th class="text-center">Obs.</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- template-row -->
                                <tr template-row style="display: none;">
                                    <td template-field="block_number" style="width: 160px" class="text-left">
                                        <input template-field="new_block_number" type="text" class="form-control input_number text-left" placeholder="Block Number" maxlength="50" style="padding:3px;">
                                    </td>
                                    <td template-field="tot_c" style="width: 60px" class="text-right">{C}</td>
                                    <td template-field="tot_a" style="width: 60px" class="text-right">{A}</td>
                                    <td template-field="tot_l" style="width: 60px" class="text-right">{L}</td>
                                    <td template-field="sale_net_c" style="width: 60px" class="text-right">{C}</td>
                                    <td template-field="sale_net_a" style="width: 60px" class="text-right">{A}</td>
                                    <td template-field="sale_net_l" style="width: 60px" class="text-right">{L}</td>
                                    <td template-field="sale_net_vol" style="width: 80px" class="text-right">{Vol}</td>
                                    <td template-field="tot_weight" style="width: 90px" class="text-right">{Weight}</td>
                                    <td template-field="obs">{Obs}</td>
                                </tr>
                                <!-- /template-row -->
                            </tbody>
                        </table>
                        
                    </div>

                </div>
                <!-- /template-table -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_confirm_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_confirm_ok">Confirm</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->