<!-- MODAL DETALHE -->
<div class="modal" tabindex="-1" role="dialog" id = "modal_inspection_notification" aria-labelledby="modal_inspection_notification_label" aria-hidden="true" onload="javascript: show_dialog();">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn_cancelar close" onclick="javascript: close_modal();" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal_inspection_notification_label">Inspection Notification</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="modal_inspection_notification_edt_email" onload="javascript: carrega_email();">E-mail</label>
                    <input type="text" class="edt_email form-control" maxlength="500">
                </div>

                <div class="row">

                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover tab_list_notification_group">
                                <thead>
                                    <tr>
                                        <th class="text-center">Client Group</th>
                                        <th class="text-center">E-mail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr template-row style="display: none">
                                        <td template-field="group_name">{group_name}</td>
                                        <td>
                                            <div class="form-group">
                                                <input class="form-control" template-field="edt_email">
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn_cancel btn btn-default" onclick="javascript: close_modal();">Cancel</button>
                <button type="button" class="btn_save btn btn-primary" onclick="javascript: save_inspection_notification();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->