<!-- MODAL DETALHE -->
<div class="modal" id="modal_refuse" tabindex="-1" role="dialog" aria-labelledby="modal_refuse_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_refuse');">&times;</button>
                <h4 class="modal-title" id="modal_refuse_label">Refuse</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="refuse_post_tipo">

                    <input type="hidden" id="refuse_rec_id">

                    <div class="form-group">
                        <label for="edt_refuse_block_number">Block Number</label>
                        <input type="text" class="form-control" id="edt_refuse_block_number" placeholder="Block Number" readonly="true">
                    </div>

                    <div class="form-group" id="refuse_client_block_number">
                        <label for="edt_refuse_reason">Reason</label>
                        <textarea class="form-control" id="edt_refuse_reason" placeholder="Reason cause" rows="4" maxlength="500" spellcheck="false"></textarea>
                    </div>

                </form>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_refuse_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_refuse_ok">Refuse</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->