<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">Travel Plan Template</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="post_tipo" name="post_tipo">
                <input type="hidden" id="rec_id">

                <div class="form-group">
                    <label for="edt_description">Description</label>
                    <input type="text" class="form-control" id="edt_description" placeholder="Description" maxlength="50">
                </div>

                <!-- Listagem de rotas -->
                <div class="table-responsive">
                    
                    <table class="table table-striped table-hover" id="tbl_routes">
                        <thead>
                            <tr>
                                <th>Start</th>
                                <th>End</th>
                                <th>Time (days)</th>
                                <th class="text-right">
                                    <a id="btn_add_route" class="btn btn-default" onclick="javascript:show_dialog_route(last_end_quarry_id, last_end_terminal_id)">
                                      <span class="glyphicon glyphicon-plus"></span>
                                    </a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- itens -->
                            <tr template-row style="display: none;">
                                <!--td template-field="id">{id}</td-->
                                <td template-field="start_location">{start_location}</td>
                                <td template-field="end_location">{end_location}</td>
                                <td template-field="shipping_time">{shipping_time}</td>
                                <td style="text-align: right;">
                                    <div class="btn-group" style="text-align: left;">
                                        <button type="button" class="btn btn-default btn-xs" template-button="remove">
                                            Remove
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                </div>
                <!-- /Listagem de rotas -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->