<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe_add_route" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_add_route_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_add_route');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_add_route_label">Travel Route</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="cbo_start">Start</label>
                    <select id="cbo_start" class="form-control select2 select2-input">
                    </select>
                </div>
                
                <!-- Locations -->
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="tbl_list_end">
                        <thead>
                            <tr>
                                <th>End</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- itens -->
                            <tr template-row style="display: none;">
                                <td template-field="end_location">{end_location}</td>
                                <td style="text-align: right;">
                                    <div class="btn-group" style="text-align: left;">
                                        <button type="button" class="btn btn-primary" template-button="select">
                                            <span class="glyphicon glyphicon-ok"></span> Select
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Locations -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe_add_route');">Cancel</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->