<!-- MODAL LISTA BLOCOS -->
<div class="modal bs-modal-lg" id="modal_add_block" tabindex="-1" role="dialog" aria-labelledby="modal_add_block_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_add_block');">&times;</button>
                <h4 class="modal-title" id="modal_add_block_label">Start the logistic <span id="modal_add_block_client_name">{client_name}</span></h4>
            </div>
            <div class="modal-body">

                <!-- template-table -->
                
                <div class="table-responsive">
                    <table id="table_block_list_add" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Block Number</th>
                                <th class="text-center">Quality</th>
                                <th class="text-center">Production Date</th>
                                <!--th class="text-center">Inspection</th -->
                                <th class="text-center">Inspection Date</th>
                                <th class="text-center">
                                    <button type="button" class="btn btn-xs btn-default" template-button="uncheck_all">
                                        <span class="glyphicon glyphicon-unchecked"></span>
                                    </button>
                                    <button type="button" class="btn btn-xs btn-default" template-button="check_all">
                                        <span class="glyphicon glyphicon-check"></span>
                                    </button>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- template-row -->
                            <tr template-row style="display: none;">
                                <td template-field="block_number" style="width: 160px">
                                    <a template-field="block_number_a" href="#">{block_number}</a>
                                </td>
                                <td template-field="quality_name" style="width: 60px" class="text-center">{quality_name}</td>
                                <td template-field="date_production" style="width: 100px" class="text-center">{date_production}</td>
                                <!--td template-field="invoice_id" style="width: 60px" class="text-center">{invoice_id}</td -->
                                <td template-field="invoice_date_record" style="width: 100px" class="text-center">{invoice_date_record}</td>

                                <td template-field="selected" style="width: 70px" class="text-center">
                                    <input type="checkbox">
                                </td>
                            </tr>
                            <!-- /template-row -->
                        </tbody>
                    </table>
                </div>
                <!-- /template-table -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_add_block_cancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_add_block_add">Ok</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL LISTA BLOCOS -->