<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_detalhe_dismember" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_dismember_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_dismember');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_dismember_label">Dismember Lot</h4>
            </div>
            <div class="modal-body">
                <div class="row">

                    <div class="col-sm-6">
                        
                        <!-- lot old -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <span id="dis_title_lot_number_orig">{lot_number}</span>
                                </h3>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover" id="tbl_dis_orig">
                                    <thead>
                                        <tr>
                                            <th>Block Number</th>
                                            <th>Quality</th>
                                            <th>Location</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- itens -->
                                        <tr template-row style="display: none;">
                                            <td template-field="block_number">{block_number}</td>
                                            <td template-field="quality">{quality}</td>
                                            <td>
                                                <span template-field="destination">{destination}</span>
                                                <br/><span template-field="status">{status}</span>
                                            </td>
                                            <td>
                                                <div class="pull-right">
                                                    <button type="button" class="btn btn-primary" template-button="select">
                                                        Move <span class="glyphicon glyphicon-chevron-right"></span>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /lot old -->
                    </div>
                    
                    <div class="col-sm-6">
                        
                        <!-- lot new -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">New Lot</h3>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover" id="tbl_dis_new">
                                    <thead>
                                        <tr>
                                            <th>Block Number</th>
                                            <th>Quality</th>
                                            <th>Location</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- itens -->
                                        <tr template-row style="display: none;">
                                            <td template-field="block_number">{block_number}</td>
                                            <td template-field="quality">{quality}</td>
                                            <td>
                                                <span template-field="destination">{destination}</span>
                                                <br/><span template-field="status">{status}</span>
                                            </td>
                                            <td>
                                                <div class="pull-right">
                                                    <button type="button" class="btn btn-primary" template-button="select">
                                                        <span class="glyphicon glyphicon-chevron-left"></span> Undo
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- /lot new -->
                    </div>

                </div>
            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" onclick="javascript:closeModal('modal_detalhe_dismember');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_next" onclick="javascript:dic_show_dialog_confirm();">Next Step</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->