<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe_dismember_confirm" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_dismember_confirm_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_dismember_confirm');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_dismember_label">New Lot</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                            
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="edt_dic_lot_number">Number</label>
                            <input type="text" class="form-control" id="edt_dic_lot_number" placeholder="Lot Number" maxlength="50">
                        </div>
                    </div>
                        
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="tbl_dic_new">
                            <thead>
                                <tr>
                                    <th>Block Number</th>
                                    <th>Quality</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- itens -->
                                <tr template-row style="display: none;">
                                    <td template-field="block_number">{block_number}</td>
                                    <td template-field="quality">{quality}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                  
                </div>
            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" onclick="javascript:closeModal('modal_detalhe_dismember_confirm');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_dic_confirm" onclick="javascript:dic_confirm();">Confirm</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->