<ol class="breadcrumb">
    <li><a>Logistics</a></li>
    <li class="active">Lots</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary btn_lt_new">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:refresh_listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>

        <div class="pull-right">
            <label for="cbo_filter_client">Filter lots of client</label>
            <select id="cbo_filter_client" class="form-control select2 select2-input">
            </select>
        </div>
    </nav>

    <!-- Listagem de pedreiras -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <!--th>#</th-->
                    <th>Lot Number</th>
                    <th>Client</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Blocks</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <!--td template-field="id">{id}</td-->
                    <td template-field="lot_number">{lot_number}</td>
                    <td template-field="client_name">{client_name}</td>
                    <td template-field="date_record">{date_record}</td>
                    <td><span template-field="status">{status}</span></td>
                    <td template-field="items_count">{items_count}</td>
                    <td>
                        <div class="btn-group" style="float: right;">

                            <a href="#" class="btn btn-default" template-button="blocks">
                                <!--span class="glyphicon glyphicon-th-large"></span--> Blocks
                            </a>

                            <!--a href="#" class="btn btn-default" template-button="travel_plan">
                                Travel Plan
                            </a-->

                            <a href="#" class="btn btn-default" template-button="release">
                                <!--span class="glyphicon glyphicon-thumbs-up"></span--> Release
                            </a>
                            
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    Action <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li template-menu="dismember"><a href="#" template-button="dismember">
                                        Dismember
                                    </a></li>
                                    <li class="divider">
                                    <li template-menu="delete"><a href="#" template-button="delete">
                                        Delete
                                    </a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->