<ol class="breadcrumb">
    <li><a>Logistics</a></li>
    <li class="active">Lots</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <div class="row">
            <div class="col-md-2" style="padding-top: 25px;">
                <button type="button" class="btn btn-primary btn_lt_new">
                    <span class="glyphicon glyphicon-plus-sign"></span> New
                </button>
                <button type="button" class="btn_refresh btn btn-default" onclick="javascript:refresh_listar()" disabled="disabled">
                    <span class="glyphicon glyphicon-refresh"></span>
                </button>
            </div>
            
            <div class="col-md-2">
                <div class="form-group">
                    <label>&nbsp;</label>
                    <input type="text" class="form-control" placeholder="Year" maxlength="4" id="edt_year">
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label class="hidden-sm hidden-xs">&nbsp;</label>
                    <select id="cbo_month_filter" class="form-control select2 select2-input">  
                        <option value="01">January</option>
                        <option value="02">February</option>
                        <option value="03">March</option>
                        <option value="04">April</option>
                        <option value="05">May</option>
                        <option value="06">June</option>
                        <option value="07">July</option>
                        <option value="08">August</option>
                        <option value="09">September</option>
                        <option value="10">Octuber</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select>
                </div>
            </div>
            
            <div class="col-md-5">
                <div class="form-group">
                    <label for="cbo_filter_client">Filter lots of client</label>
                    <select id="cbo_filter_client" class="form-control select2 select2-input">
                    </select>
                </div>
            </div>
        </div>
    </nav>

    <!-- Listagem de pedreiras -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <!--th>#</th-->
                    <th width="150px">Lot Number</th>
                    <th>Client</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Blocks</th>
                    <th width="250px">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <!--td template-field="id">{id}</td-->
                    <td template-field="lot_number">{lot_number}</td>
                    <td template-field="client_name">{client_name}</td>
                    <td template-field="date_record">{date_record}</td>
                    <td><span template-field="status">{status}</span></td>
                    <td template-field="items_count">{items_count}</td>
                    <td>
                        <div class="btn-group" style="float: right;">

                            <a href="#" class="btn btn-default" template-button="blocks">
                                <!--span class="glyphicon glyphicon-th-large"></span--> Blocks
                            </a>

                            <!--a href="#" class="btn btn-default" template-button="travel_plan">
                                Travel Plan
                            </a-->

                            <a href="#" class="btn btn-default" template-button="release">
                                <!--span class="glyphicon glyphicon-thumbs-up"></span--> Release
                            </a>
                            
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    Action <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li template-menu="dismember"><a href="#" template-button="dismember">
                                        Dismember
                                    </a></li>
                                    <li class="divider">
                                    <li template-menu="delete"><a href="#" template-button="delete">
                                        Delete
                                    </a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->