<ol class="breadcrumb">
    <li><a>Production</a></li>
    <li class="active">Production Orders</li>
</ol>


<div>
    <div class="row">
        <div class="col-md-2" style="width: 150px;">
            <label>&nbsp;</label>
            <input type="text" class="form-control" placeholder="Year" maxlength="4" id="edt_year" onkeyup="javascript:listar()">
        </div>
        <div class="form-group col-md-3">
            <label>&nbsp;</label>
            <select id="cbo_month_filter" class="form-control select2 select2-input" onchange="javascript:listar()">  
                <option value="01">January</option>
                <option value="02">February</option>
                <option value="03">March</option>
                <option value="04">April</option>
                <option value="05">May</option>
                <option value="06">June</option>
                <option value="07">July</option>
                <option value="08">August</option>
                <option value="09">September</option>
                <option value="10">Octuber</option>
                <option value="11">November</option>
                <option value="12">December</option>
            </select>
        </div>
        <div class="col-md-3">
            <label for="cbo_filter_type">Filter Block Type</label>
            <select id="cbo_filter_type" class="form-control select2 select2-input" onchange="javascript:listar()">
                <option value="-1">All</option>
                <option value="1">Final Block</option>
                <option value="2">Interim Block</option>
            </select>
        </div>
        <div class="col-md-3">
            <label for="cbo_filter_quarry">Filter Quarry</label>
            <select id="cbo_filter_quarry" class="form-control select2 select2-input">
            </select>
        </div>   
    </div>
    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav>

    <!-- Listagem de chamados -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>Quarry</th>
                    <th>Production Date</th>
                    <th>Block Type</th>
                    <th>Status</th>
                    <th>Vol</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="quarry_name">{quarry_name}</td>
                    <td template-field="date_production">{date_production}</td>
                    <td template-field="block_type">{block_type}</td>
                    <td><span template-field="status">{status}</span></td>
                    <td><span template-field="vol">{vol}</span></td>
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                <li><a href="#" template-button="edit">
                                    Edit
                                </a></li>
                                <li><a href="#" template-button="delete">
                                    Delete
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- /Listagem de chamados -->

</div>