<ol class="breadcrumb">
    <li><a>Production</a></li>
    <li class="active">Production Orders</li>
</ol>


<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav>

    <!-- Listagem de chamados -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>Quarry</th>
                    <th>Production Date</th>
                    <th>Block Type</th>
                    <th>Status</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="quarry_name">{quarry_name}</td>
                    <td template-field="date_production">{date_production}</td>
                    <td template-field="block_type">{block_type}</td>
                    <td><span template-field="status">{status}</span></td>
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                <li><a href="#" template-button="edit">
                                    Edit
                                </a></li>
                                <li><a href="#" template-button="delete">
                                    Delete
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- /Listagem de chamados -->

</div>