<ol class="breadcrumb">
    <li><a>General</a></li>
    <li class="active">Blocks</li>
</ol>

<div class="row">
    <div class="col-md-4">
         <div class="form-group">
            <label for="cbo_filter_block">Filter by block number</label>
            <input type="text" class="form-control edt_filter_block"></input>
        </div>
    </div>
    <div class=" col-md-4">
         <div class="form-group">
            <label for="cbo_filter_client">Filter by client</label>
            <select id="cbo_filter_client" class="form-control select2 select2-input">
            </select>
        </div>
    </div>
</div>

<!-- LISTAGEM -->
<div>

    <!--nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav-->

    <!-- Listagem de pedreiras -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>Block Number</th>
                    <th>Type</th>
                    <th>Reserved</th>
                    <th>Sold</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="block_number">{block_number}</td>
                    <td template-field="type">{type}</td>
                    <td template-field="reserved">{reserved}</td>
                    <td template-field="sold">{sold}</td>
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default <?= (!verifica_acesso('block_change', $permissions) ? 'disabled' : '') ?> " template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                
                                <li class=" <?= (!verifica_acesso('block_change', $permissions) ? 'disabled' : '') ?>">
                                    <a <?= (!verifica_acesso('block_change', $permissions) ? '' : 'href="#" template-button="edit"' ) ?> >
                                        Edit
                                    </a>
                                </li>
                                <li class=" <?= (!verifica_acesso('block_change', $permissions) ? 'disabled' : '') ?>">
                                    <a  <?= (!verifica_acesso('block_change', $permissions) ? '' :'href="#" template-button="delete"' ) ?> >
                                        Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->