<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_search_block" tabindex="-1" role="dialog" aria-labelledby="modal_search_block_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_search_block');">&times;</button>
                <h4 class="modal-title" id="modal_search_block_label">Block</h4>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-xs-8 col-sm-5">
                        <div class="form-group">
                                <input type="text" class="form-control" id="edt_search_block_number" placeholder="Block Number">
                        </div>
                    </div>
                    <div class="col-xs-2 col-sm-1">
                        <div class="form-group">
                            <button class="btn btn-primary" type="button" id="btn_search_block_number">
                                <span class="glyphicon glyphicon-search"></span> Search
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Listagem blocos -->
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="tbl_search_block">
                        <thead>
                            <tr>
                                <th>Block Number</th>
                                <th>Quality</th>
                                <th>Client</th>
                                <th>Lot</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- itens -->
                            <tr template-row style="display: none;">
                                <td template-field="block_number">{block_number}</td>
                                <td template-field="quality_name">{quality_name}</td>
                                <td template-field="sold_client_code">{sold_client_code}</td>
                                <td template-field="lot">{lot}</td>
                                <td style="text-align: right;">
                                    <div class="btn-group" style="text-align: left;">
                                        <button type="button" class="btn btn-primary" id="btn_save" template-button="select">Select</button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Listagem blocos -->

            </div>

            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_search_block');">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!-- /MODAL DETALHE -->