<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe_import_template" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_import_template_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_import_template');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_import_template_label">Import Template</h4>
            </div>
            <div class="modal-body">
                
                <!-- Templates -->
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="tbl_templates">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- itens -->
                            <tr template-row style="display: none;">
                                <td template-field="description">{description}</td>
                                <td style="text-align: right;">
                                    <div class="btn-group" style="text-align: left;">
                                        <button type="button" class="btn btn-primary" template-button="select">
                                            <span class="glyphicon glyphicon-ok"></span> Select
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /Templates -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe_import_template');">Cancel</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->