<!-- LISTAGEM -->
<div class="row" id="div_travel_plan">
    
    <div class="col-sm-12 col-md-8">

        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="pull-left">
                
                    <div class="checkbox" id="div_chk_client_remove">
                        <label>
                            <input id="chk_client_remove" type="checkbox" value="">
                            The client will remove the blocks from the quarry
                        </label>
                    </div>
                    <div class="checkbox" id="div_chk_local_market">
                        <label>
                            <input id="chk_local_market" type="checkbox" value="">
                            Local market
                        </label>
                    </div>
                </div>
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary" id="btn_add_travel" onclick="javascript:tp_show_dialog(last_end_quarry_id, last_end_terminal_id)">
                            <span class="glyphicon glyphicon-plus-sign"></span> Add route
                        </button>
                        <button type="button" class="btn btn-primary" id="btn_import_template" onclick="javascript:show_dialog_import_template()">
                            Import template
                        </button>
                    </div>
                </div>
                
                <div class="clearfix"></div>
            </div>

            

            <!-- Listagem de chamados -->
            <div class="table-responsive">
                
                <table class="table table-striped table-hover" id="tbl_tp_listagem">
                    <thead>
                        <tr>
                            <th>Start</th>
                            <th>End</th>
                            <th>Time (days)</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- itens -->
                        <tr template-row style="display: none;">
                            <!--td template-field="id">{id}</td-->
                            <td template-field="start_location">{start_location}</td>
                            <td template-field="end_location">{end_location}</td>
                            <td template-field="shipping_time">{shipping_time}</td>
                            <td style="text-align: right;">
                                <div class="btn-group" style="text-align: left;">
                                    <button type="button" class="btn btn-default btn-xs" template-button="remove">
                                        Remove
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <!-- /Listagem de chamados -->
        </div>


    </div>

    <div class="col-sm-12 col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                Logistical history
            </div>

            <div class="list-group table-striped">
                <div class="list-group-item" id="list_history">
                </div>
            </div>

            <div class="row" id="template_history" style="padding-bottom: 8px; display: none;">
                <div class="col-xs-6">
                    <span template-field="date" class="small">{date}</span>
                    <br>
                    <span template-field="block_number">{block_number}</span>
                </div>
                <div class="col-xs-6">
                    <span template-field="destination" class="small">{destination}</span>
                    <br>
                    <span template-field="status">{status}</span>
                </div>
            </div>
        </div>

    </div>


</div>
<!-- /LISTAGEM -->