<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label">Travel Route</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    
                    <input type="hidden" id="post_tipo" name="post_tipo">

                    <input type="hidden" id="rec_id">

                    <div class="form-group">
                        <label for="cbo_start">Start</label>
                        <select id="cbo_start" class="form-control select2 select2-input">
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="cbo_end">End</label>
                        <select id="cbo_end" class="form-control select2 select2-input">
                        </select>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="edt_shipping_time">Shipping Time (days)</label>
                                <input type="text" class="form-control input_integer" id="edt_shipping_time" placeholder="0">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="edt_blocks">Blocks (per travel)</label>
                                <input type="text" class="form-control input_integer" id="edt_blocks" placeholder="0">
                            </div>
                        </div>
                    </div>

                </form>
                
                <!-- ALERTAS -->
                <div id="alerta_form" class="alert alert-danger">
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->