<ol class="breadcrumb">
    <li><a>Logistics</a></li>
    <li class="active">Travel Route</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav>

    <!-- Listagem -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <!--th>#</th-->
                    <th>Start</th>
                    <th>End</th>
                    <th>Time (days)</th>
                    <th>Blocks (per travel)</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <!--td template-field="id">{id}</td-->
                    <td template-field="start_location">{start_location}</td>
                    <td template-field="end_location">{end_location}</td>
                    <td template-field="shipping_time">{shipping_time}</td>
                    <td template-field="blocks">{blocks}</td>
                    <td style="text-align: right;">
                        <div class="btn-group" style="text-align: left;">
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Action <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#" template-button="visualize">
                                    Visualize
                                </a></li>
                                <li><a href="#" template-button="edit">
                                    Edit
                                </a></li>
                                <li><a href="#" template-button="delete">
                                    Delete
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem -->

</div>
<!-- /LISTAGEM -->