<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_detalhe_reinspection_block" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_reinspection_block_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_reinspection_block');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_reinspection_block_label">Reinspection <span id="lbl_reinspection_block_number"></span></h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="rec_reinspection_id"/>
                <input type="hidden" id="product_weight_vol"/>
                
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="tbl_dis_orig">
                        <thead>
                            <tr>
                                <th width="100px">&nbsp;</th>
                                <th colspan="3">Old Value</th>
                                <th colspan="3">New Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><b>Tot Meas</b></td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_old_tot_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_old_tot_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_old_tot_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_new_tot_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_new_tot_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_new_tot_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                            </tr>
                            <tr>
                                <td><b>Net Meas</b></td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_old_net_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_old_net_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_old_net_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_new_net_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_new_net_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_new_net_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                    <input id="edt_reinspection_new_net_vol" type="hidden">
                                </td>
                            </tr>
                            <tr>
                                <td><b>Client Net Meas</b></td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_old_sale_net_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_old_sale_net_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_old_sale_net_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;" readonly="readonly">
                                </td>
                                <td style="width: 80px" class="text-right meas_c">
                                    <input id="edt_reinspection_new_sale_net_c" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_a">
                                    <input id="edt_reinspection_new_sale_net_a" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                </td>
                                <td style="width: 80px" class="text-right meas_l">
                                    <input id="edt_reinspection_new_sale_net_l" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 80px;">
                                    <input id="edt_reinspection_new_sale_net_vol" type="hidden">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        
                    </div>
                    <div class="col-md-2 text-right">
                        <div class="form-group">
                            <label for="edt_reinspection_vol">Vol</label>
                            <input type="text" class="form-control text-right" id="edt_reinspection_vol" placeholder="0.00" readonly="readonly">
                        </div>
                    </div>
                    <div class="col-md-2 text-right">
                        <div class="form-group">
                            <label for="edt_reinspection_weight">Weight</label>
                            <input type="text" class="form-control text-right" id="edt_reinspection_weight" placeholder="0.00" readonly="readonly">
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" onclick="javascript:closeModal('modal_detalhe_reinspection_block');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_reinspection_block_confirm">Confirm</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->