<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_start_shipping" tabindex="-1" role="dialog" aria-labelledby="modal_start_shipping_label" aria-hidden="true" style="font-size: 12px;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_start_shipping');">&times;</button>
                <h4 class="modal-title" id="modal_start_shipping_label">Start Transportation</h4>
            </div>
            <div class="modal-body">
                
                <div id="list_start_shipping">
                </div>

                <!-- template-table -->
                <div class="panel panel-default" style="display: none;" template-table="start_shipping">
                    <div class="panel-heading" style="padding: 5px" >
                        
                        
                        <div class="row ">
                            <div class=" pull-left col-md-6">
                                <h3 class="panel-title" style="font-weight: bold" template-title>Lote</h3>
                            </div>


                            <div class="col-md-4 pull-right div_trucks hidden">
                               
                                <button type="button" class="pull-right btn_new_truck btn btn-default">
                                    Add Truck
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                                    
                            </div>


                        </div>
                        
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="travel_plan">
                            <thead>
                                <tr>
                                    <th style="width: 100px">Block Number</th>
                                    <th style="width: 90px">NF</th>
                                    <th style="width: 130px">Date NF</th>
                                    <th style="width: 90px" class="text-right">Price</th>
                                    <th width="90px" class="colun_wagon text-center">Wagon</th>
                                    <!--th colspan="3" class="text-center">Tot Meas</th-->
                                    <th class="text-center">Net Meas</th>
                                    <th >Truck</th>
                                    <th width="90px" template-header="destination">Destination</th>           
                                </tr>
                            </thead>
                            <tbody>
                                <!-- itens -->
                                <tr template-row style="display: none;">
                                    
                                    <td template-field="block_number">
                                        <span template-field="block_number_a">{block_number}</span>
                                    </td>
     
                                    <td class="text-left" template-field="nf">
                                        <input template-field="nf_edit" type="text" class="form-control text-left" placeholder="Enter" maxlength="50" style="padding:3px; width: 80px;">
                                    </td>

                                    <td class="text-left" template-field="date_nf">
                                        <input template-field="date_nf_edit" type="date" class="form-control" style="padding:3px; width: 130px;">
                                    </td>

                                    <td class="text-right" template-field="price">
                                        <input template-field="price_edit" type="text" class="form-control input_number text-right" placeholder="0.00" style="padding:3px; width: 70px;">
                                    </td>

                                    <td width="90px" class="text-left colun_wagon" template-field="wagon_number" >
                                        <input template-field="wagon_number_edit" type="text" class="form-control text-left small" placeholder="Enter" style="padding:3px; width: 120px;">
                                    </td>

                                    <td style="width: 45px" class="text-center" >
                                        <span template-field="sale_net_c" >{C}</span>
                                        <br>
                                        <span template-field="sale_net_a">{A}</span>
                                        <br>
                                        <span template-field="sale_net_l">{L}</span>
                                        <br>
                                        <span template-field="sale_net_vol">{sale_net_vol}</span>
                                        <br>
                                        <span template-field="tot_weight" >{weight}</span>
                                    </td>
                                    <td template-field="truck">
                                        <select id="cbo_trucks" class="div_trucks hidden form-control ">
                                        </select>
                                    </td>
                                    <td width="90px"  template-field="destination">{destination}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /template-table -->

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" onclick="javascript:closeModal('modal_start_shipping');">Cancel</button>
                
                <button type="button" class="btn btn-info" id="btn_client_removed" onclick="javascript:btn_start_shipping_click(DLG_POINTING_TRAVEL.CLIENT_REMOVED);">
                    <span class="glyphicon glyphicon-ok"></span> The client removed
                </button>
                <button type="button" class="btn btn-success" id="btn_start_shipping" onclick="javascript:btn_start_shipping_click(DLG_POINTING_TRAVEL.START_SHIPPING);">
                    <span class="glyphicon glyphicon-road"></span> Start transportation
                </button>
                <button type="button" class="btn btn-warning" id="btn_mark_completed" onclick="javascript:btn_mark_completed_click();">
                    <span class="glyphicon glyphicon-flag"></span> Mark as completed
                </button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->