<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:cancela_modal();">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_label"></h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">

                    <input type="hidden" id="rec_id">
                    <input type="hidden" id="post_tipo">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="edt_price_date">Date Ref</label>
                                        <input type="date" class="form-control" id="edt_price_date">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="edt_price_comments">Comments</label>
                                        <textarea class="form-control" id="edt_price_comments" rows="15"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="list_price_products">
                            </div>
                        </div>
                    </div>


                    <!-- template-painel-client-group -->
                    <div class="panel panel-default small" style="display: none;" template-panel-product-price>
                        <div class="panel-heading" style="padding: 5px" >
                            <h3 class="panel-title" style="font-weight: bold" template-name>{Product}</h3>
                        </div>
                        <table class="table table-striped table-bordered table-hover table_client_products">
                        </table>
                    </div>
                    <!-- /template-painel-client-group -->

                </form>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:cancela_modal();">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->