<!-- MODAL DETALHE -->
<div class="modal bs-modal-lg" id="modal_price_history" tabindex="-1" role="dialog" aria-labelledby="modal_price_history" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width: 95%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_price_history');">&times;</button>
                <h4 class="modal-title" id="modal_price_history_title">History</h4>
            </div>
            <div class="modal-body" style="padding-left: 0px; padding-bottom: 0px; padding-right: 0px; padding-top: 0px;">

                <div class="table-responsive small">
                    <table class="table table-striped table-bordered table-hover small" id="table_client_history">
                    </table>
                </div>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_price_history');">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->