<ol class="breadcrumb">
    <li><a>Settings</a></li>
    <li class="active">Users</li>
</ol>

<!-- LISTAGEM -->
<div>

    <nav class="navbar" role="navigation" style="margin: 0px; padding: 0px;">
        <button type="button" class="btn btn-primary" onclick="javascript:show_dialog(FORMULARIO.NOVO);">
            <span class="glyphicon glyphicon-plus-sign"></span> New
        </button>
        <button type="button" class="btn btn-default" onclick="javascript:listar()">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </nav>

    <!-- Listagem de pedreiras -->
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="tbl_listagem">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Blocked</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <!-- itens -->
                <tr template-row style="display: none;">
                    <td template-field="name">{name}</td>
                    <td template-field="blocked">{blocked}</td>
                    
                    <td template-buttons="actions">
                        <div class="btn-group" style="float: right;">
                            <button type="button" class="btn btn-default" template-button="permission">
                                <span class="glyphicon glyphicon-lock"></span> Permissions
                            </button>
                            <button type="button" class="btn btn-default" template-button="edit">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    Action <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#" template-button="visualize">
                                        Visualize
                                    </a></li>
                                    <li><a href="#" template-button="edit">
                                        Edit
                                    </a></li>
                                    <li><a href="#" template-button="delete">
                                        Delete
                                    </a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /Listagem de chamados -->

</div>

<!-- /LISTAGEM -->