<!-- MODAL DETALHE -->
<div class="modal" id="modal_detalhe_permission" tabindex="-1" role="dialog" aria-labelledby="modal_detalhe_permission_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="javascript:closeModal('modal_detalhe_permission');">&times;</button>
                <h4 class="modal-title" id="modal_detalhe_permission_label">User Permissions</h4>
            </div>
            <div class="modal-body">
                <form role="form" onsubmit="javascript:return false;">
                    <input type="hidden" id="post_tipo" name="post_tipo">

                    <input type="hidden" id="rec_id">
                    <div class="form-group">
                        <label for="per_edt_user_name">User Name</label>
                        <span class="form-control" id="per_edt_user_name" readonly="true"></span>
                    </div>
                    <div class="form-group">
                        <label for="cbo_quarries">Quarries</label>
                        <select id="cbo_quarries" class="form-control select2" multiple="multiple">
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="cbo_client_groups">Client Groups</label>
                        <select id="cbo_client_groups" class="form-control select2" multiple="multiple">
                        </select>
                    </div>

                    <!-- Listagem -->
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table_block_list" id="tbl_permissions">
                            <thead>
                                <tr>
                                    <th>Permission</th>
                                    <th class="hidden-xs">Description</th>
                                    <th class="text-center">
                                        <button type="button" class="btn btn-xs btn-default" template-button="uncheck_all">
                                            <span class="glyphicon glyphicon-unchecked"></span>
                                        </button>
                                        <button type="button" class="btn btn-xs btn-default" template-button="check_all">
                                            <span class="glyphicon glyphicon-check"></span>
                                        </button>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- itens -->
                                <tr template-row style="display: none;">
                                    <!--td template-field="id">{id}</td-->
                                    <td template-field="name">{name}</td>
                                    <td template-field="description" class="hidden-xs">{description}</td>
                                    <td template-field="selected" style="width: 70px" class="text-center">
                                        <input type="checkbox">
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <!-- /Listagem -->

                </form>

            </div>
            <div class="modal-footer" style="bottom: 0px;">
                <button type="button" class="btn btn-default" id="btn_cancel" onclick="javascript:closeModal('modal_detalhe_permission');">Cancel</button>
                <button type="button" class="btn btn-primary" id="btn_save" onclick="javascript:per_envia_detalhes();">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- /MODAL DETALHE -->