<div id="item_template" template-ref="div_block" class="row" style="display: none;">

    <div class="row" style="margin-left: 10px; margin-right: 10px">
        <div class="col-sm-5">
            
            <input type="hidden" template-ref="rec_id">
            <input type="hidden" template-ref="rec_block_id">
            <input type="hidden" template-ref="rec_removed" value="false">
            <input type="hidden" template-ref="rec_block_number_exists" value="false">
            <input type="hidden" template-ref="rec_defects_json" value="">

            <div class="form-group">
                <label for="edt_block">Block Number</label>
                <input type="text" class="form-control" template-ref="edt_block" placeholder="Block Number" maxlength="50">
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-1">
                        &nbsp;
                    </div>
                    <div class="col-xs-2" style="text-align: center">
                        <label>C</label>
                    </div>
                    <div class="col-xs-2" style="text-align: center">
                        <label>A</label>
                    </div>
                    <div class="col-xs-2" style="text-align: center">
                        <label>L</label>
                    </div>
                    <div class="col-xs-3" style="text-align: center">
                        <label>M³</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-1" style="padding:0px; margin: 0px; text-align: right; margin-right: 8px;">
                        <label class="small">Tot <small>Meas</small></label>
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_tot_c" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_tot_a" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_tot_l" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-3" style="padding:0px; margin: 0px; margin-left: 3px;">
                        <input template-ref="edt_tot_vol" type="text" class="form-control input_number3" placeholder="0.000" readonly="readonly">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-1" style="padding:0px; margin: 0px; text-align: right; margin-right: 8px;">
                        <label class="small">Net <small>Meas</small></label>
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_net_c" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_net_a" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-2" style="padding:0px; margin: 0px;">
                        <input template-ref="edt_net_l" type="text" class="form-control input_number" placeholder="0.00" style="padding:3px;">
                    </div>
                    <div class="col-xs-3" style="padding:0px; margin: 0px; margin-left: 3px;">
                        <input template-ref="edt_net_vol" type="text" class="form-control input_number3" placeholder="0.000" readonly="readonly">
                    </div>
                </div>

                <div class="form-group" style="padding:0px; margin: 0px; margin-top: 15px;">
                    <div class="row">
                        <div class="col-xs-6">
                            <label for="edt_tot_weight">Tot Weight</label>
                            <input template-ref="edt_tot_weight" type="text" class="form-control input_number3" placeholder="0.000" disabled="disabled">
                        </div>
                        <div class="col-xs-6 div_block_number_interim" style="display:none">
                            <label for="edt_block_number_interim">Block Number Interim</label>
                            <input template-ref="edt_block_number_interim" type="text" class="form-control" disabled="disabled">
                        </div>
                    </div>
                </div>
                
            </div>

        </div>
        <div class="col-sm-3">
            <div class="form-group">
                <label for="edt_banccorredor">Observations</label>
                <textarea class="form-control" template-ref="edt_observations" placeholder="PC, TDI, B/C" rows="7" maxlength="100" spellcheck="false"></textarea>
            </div>

            <div class="form-group">
                <label>Quality</label>
                <select template-ref="cbo_quality" class="form-control">
                </select>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group" template-ref="cbg_defects">
                <label>Defects</label>

                <div class="checkbox" template-row style="display:none; margin-top: -8px;">
                    <label>
                        <input type="checkbox" template-field="id">
                        <span template-field="description">Exemplo</span>
                    </label>
                </div>

                <div template-ref="cbg_defect_items">
                </div>
            </div>
        </div>
    </div>
    
    <div class="row" style="margin-top: 10px; margin-left: 20px; margin-right: 10px;" >
            
        <div class="col-sm-2">
            <div class="thumbnail" style="width: 160px; height: 160px">
                <canvas template="defect_marker" width="153" height="153" viewBox="0 0 306 306" style="background-image: url('<?= ASSETS_URI ?>img/block_thumb.png'); background-repeat: no-repeat; padding: 0px; margin: 0px;">
                    <!-- adicionar elementos aqui -->
                </canvas>
            </div>
        </div>

        <div class="col-sm-9" style="margin-left: 15px;">

            <!-- lista de fotos -->
            <div class="row" template="photos">
            </div>
            <!-- /lista de fotos -->

            <!-- template photo -->
            <div class="col-xs-6 col-md-3" style="display:none;" template="photo">
                <div class="thumbnail">
                    <img src="" />
                </div>
            </div>
            <!-- /template photo -->

            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <button template-button="send_photo" type="button" class="btn btn-default btn-xs" >
                        <span class="glyphicon glyphicon-camera"></span> Send photos
                    </button>
                </div>
            </div>
        </div>
        
    </div>

    <div class="row" style="margin-top: 10px; margin-left: 10px; margin-right: 10px">
        <div class="pull-right">
            <button template-button="remove" type="button" class="btn btn-default btn-xs">Remove</button>
        </div>
    </div>

</div>